/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsystem;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Shathiya Geerthi
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */
    Connection con;
    public bill() {
        initComponents();
        createConnection();
    }
    void createConnection()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/nikildb?autoReconnect=true&useSSL=false","root","Nikil@1492");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(doctorform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex){
            Logger.getLogger(doctorform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    static float amount=0;
    static float amount1=0;
    static float amount2=0;
    static String msg="";
    static String msg1="";
    static String msg2="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        patID = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        secondname = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText(" Urine Test @ 150/-");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 120, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText(" Blood Test @ 250/-");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 148, 167, -1));

        jCheckBox3.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Cholestral Test @ 150/-");
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 399, 194, -1));

        jCheckBox4.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("ECG @ 500/-");
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 173, 150, 30));

        jCheckBox5.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("ACCP Test @ 800/-");
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 318, 197, -1));

        jCheckBox6.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox6.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("CT Scan @ 5000/-");
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 449, 153, -1));

        jCheckBox7.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setText("Bone Scan @ 4000/-");
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 371, 187, -1));

        jCheckBox8.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox8.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox8.setText("Biopsy @ 1000/-");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 346, 176, -1));

        jCheckBox9.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox9.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox9.setText("4D Scan @ 2500/-");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 203, 167, -1));

        jCheckBox10.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox10.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox10.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox10.setText("Allergy Test @ 2200/-");
        getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 290, 176, -1));

        jCheckBox11.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox11.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox11.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox11.setText("2D Echo @ 1200/-");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 237, 164, -1));

        jCheckBox14.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox14.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox14.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox14.setText("RTPCR Test @ 4000/-");
        getContentPane().add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 477, 176, -1));

        jCheckBox15.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox15.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox15.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox15.setText("DNA Test @ 10000/-");
        getContentPane().add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 502, 176, -1));

        jCheckBox16.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox16.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox16.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox16.setText("Hepatitus Test @ 500/-");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 424, 185, -1));

        jCheckBox17.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox17.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox17.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox17.setText("Globulin Test @ 150/-");
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 265, 189, -1));

        jCheckBox18.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox18.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox18.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox18.setText("HIV Test @ 500/-");
        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 527, 176, -1));

        jCheckBox19.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox19.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox19.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox19.setText("Iron Test @ 400/-");
        getContentPane().add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 552, 213, -1));

        jCheckBox20.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox20.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox20.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox20.setText("MRI Scan 5500/-");
        getContentPane().add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 580, 153, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Surgeries");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 76, 141, 42));

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jButton1.setText("Generate Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 182, 64));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tests");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 76, 103, 42));

        jCheckBox12.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox12.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox12.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox12.setText("Cataract Removal @ 230000");
        getContentPane().add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 120, 221, -1));

        jCheckBox13.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox13.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox13.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox13.setText(" C Section @ 300000");
        getContentPane().add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 148, -1, -1));

        jCheckBox21.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox21.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox21.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox21.setText("Joint Replacement @ 1200000");
        jCheckBox21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox21ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 178, 221, -1));

        jCheckBox22.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox22.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox22.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox22.setText("Broken Bone Repair @ 600000");
        getContentPane().add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 237, -1, -1));

        jCheckBox23.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox23.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox23.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox23.setText("AngioPlasty @ 15000000");
        getContentPane().add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 265, -1, -1));

        jCheckBox24.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox24.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox24.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox24.setText("Circumcision @ 20000");
        getContentPane().add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 203, -1, -1));

        jCheckBox25.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox25.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox25.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox25.setText("Stent Procedure @ 1300000");
        getContentPane().add(jCheckBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 290, -1, -1));

        jCheckBox27.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox27.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox27.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox27.setText("Hysterectomy @ 100000");
        jCheckBox27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox27ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 318, 190, -1));

        jCheckBox28.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox28.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox28.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox28.setText("Heart Bypass Surgery @ 15000000");
        jCheckBox28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox28ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox28, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 371, 505, -1));

        jCheckBox29.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox29.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox29.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox29.setText("Cholecystectomy @ 240000");
        getContentPane().add(jCheckBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 346, -1, -1));

        jCheckBox30.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox30.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox30.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox30.setText("Kidney Stone Removal @ 200000");
        jCheckBox30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox30ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox30, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 399, -1, -1));

        jCheckBox31.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox31.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox31.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox31.setText("Colon Cancer Treatment @ 500000");
        jCheckBox31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox31ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox31, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 424, -1, -1));

        jCheckBox32.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox32.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox32.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox32.setText(" Liver Transplant @ 2400000");
        getContentPane().add(jCheckBox32, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 449, -1, -1));

        jCheckBox33.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox33.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox33.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox33.setText("Vasectomy @ 500000");
        getContentPane().add(jCheckBox33, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 502, -1, -1));

        jCheckBox34.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox34.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox34.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox34.setText("Stomach Cancer @ 600000");
        getContentPane().add(jCheckBox34, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 477, -1, -1));

        jCheckBox35.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox35.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox35.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox35.setText("Otoplasty @ 150000");
        jCheckBox35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox35ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox35, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 527, -1, -1));

        jCheckBox36.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox36.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox36.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox36.setText("Piles Surgery @ 150000");
        getContentPane().add(jCheckBox36, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 552, -1, -1));

        jCheckBox37.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox37.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jCheckBox37.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox37.setText("Spinal Fusion @ 850000");
        getContentPane().add(jCheckBox37, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 580, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Room Details");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 76, 149, 42));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setText("No. of Days:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 124, 87, 27));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 127, 106, 25));

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Full electric @ 9000/day");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 159, 185, -1));

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Semi Electric @ 8000/day");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 184, 193, -1));

        jRadioButton3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Manual @ 6000/day");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 209, 161, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 410, 370));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Patient ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 76, 130, 40));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("First Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 130, 30));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Second Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 160, 40));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Age");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, 130, 40));

        search.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 530, 170, 70));

        patID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patIDActionPerformed(evt);
            }
        });
        getContentPane().add(patID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 72, 220, 40));
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 132, 220, 40));
        getContentPane().add(secondname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 192, 220, 40));
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 262, 220, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 660, 190, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/Black.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 1230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox18ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //JOptionPane.showMessageDialog(this,msg+"Total: "+amount+ "/-");     
    if(jCheckBox1.isSelected())
        {
            amount+=150;
            msg="Urine Test: 150/-\n";
        } 
        if(jCheckBox2.isSelected())
        {
            amount+=250;
            msg+="Blood Test: 250/-\n";
        } 
        if(jCheckBox4.isSelected())
        {
            amount+=500;
            msg+="ECG: 500/-\n";
        } 
        if(jCheckBox9.isSelected())
        {
            amount+=2500;
            msg+="4D Scan: 2500/-\n";
        } 
        if(jCheckBox11.isSelected())
        {
            amount+=120;
            msg+="2D Echo: 1200/-\n";
        } 
        if(jCheckBox17.isSelected())
        {
            amount+=250;
            msg+="Globulin Test: 150/-\n";
        } 
        if(jCheckBox10.isSelected())
        {
            amount+=2200;
            msg+="Allergy Test: 2200/-\n";
        } 
        if(jCheckBox5.isSelected())
        {
            amount+=800;
            msg+="ACCP Test: 800/-\n";
        } 
        if(jCheckBox8.isSelected())
        {
            amount+=1000;
            msg+="Biopsy: 1000/-\n";
        } 
        if(jCheckBox7.isSelected())
        {
            amount+=4000;
            msg+="Bone Scan: 4000/-\n";
        }
        if(jCheckBox3.isSelected())
        {
            amount+=150;
            msg+="Cholestral Test: 150/-\n";
        } 
        if(jCheckBox16.isSelected())
        {
            amount+=500;
            msg+="Hepatitus Test: 500/-\n";
        } 
        if(jCheckBox6.isSelected())
        {
            amount+=5000;
            msg+="CT Scan: 5000/-\n";
        } 
        if(jCheckBox14.isSelected())
        {
            amount+=4000;
            msg+="RTPCR Test: 4000/-\n";
        } 
        if(jCheckBox15.isSelected())
        {
            amount+=10000;
            msg+="DNA Test: 10000/-\n";
        } 
        if(jCheckBox18.isSelected())
        {
            amount+=500;
            msg+="HIV Test: 500/-\n";
        } 
        if(jCheckBox19.isSelected())
        {
            amount+=400;
            msg+="Iron Test: 400/-\n";
        } 
        if(jCheckBox20.isSelected())
        {
            amount+=5500;
            msg+="MRI Scan: 5500/-\n";
        }
        if(jCheckBox12.isSelected())
        {
            amount1+=230000;
            msg1+="Cataract Removal: 230000/-\n";
        }
        if(jCheckBox13.isSelected())
        {
            amount1+=300000;
            msg1+="C Section: 300000/-\n";
        }
        if(jCheckBox21.isSelected())
        {
            amount1+=12000000;
            msg1+="Joint Replacement: 12000000/-\n";
        }
        if(jCheckBox24.isSelected())
        {
            amount1+=20000;
            msg1+="Circumcision: 20000/-\n";
        }        
        if(jCheckBox22.isSelected())
        {
            amount1+=600000;
            msg1+="Broken Bone Repair: 600000/-\n";
        }
        if(jCheckBox23.isSelected())
        {
            amount1+=15000000;
            msg1+="Angioplasty: 15000000/-\n";
        }
        if(jCheckBox25.isSelected())
        {
            amount1+=1300000;
            msg1+="Stent Procedure: 1300000/-\n";
        }
        if(jCheckBox27.isSelected())
        {
            amount1+=100000;
            msg1+="Hysterectomy: 100000/-\n";
        }
        if(jCheckBox29.isSelected())
        {
            amount1+=240000;
            msg1+="Cholecystectomy: 240000/-\n";
        }
        if(jCheckBox28.isSelected())
        {
            amount1+=15000000;
            msg1+="Heart Bypass Surgery: 15000000/-\n";
        }
        if(jCheckBox21.isSelected())
        {
            amount1+=200000;
            msg1+="Kidney Stone Removal: 200000/-\n";
        }
        if(jCheckBox31.isSelected())
        {
            amount+=500000;
            msg1+="Colon Cancer Treatment: 500000/-\n";
        }
        if(jCheckBox32.isSelected())
        {
            amount1+=2400000;
            msg1+="Liver Transplant: 2400000/-\n";
        }
        if(jCheckBox34.isSelected())
        {
            amount1+=600000;
            msg1+="Stomach Cancer: 600000/-\n";
        }
        if(jCheckBox33.isSelected())
        {
            amount1+=500000;
            msg1+="Vasectomy: 500000/-\n";
        }
        if(jCheckBox35.isSelected())
        {
            amount1+=150000;
            msg1+="Otoplasty: 150000/-\n";
        }
        if(jCheckBox36.isSelected())
        {
            amount1+=150000;
            msg1+="Piles Surgery: 150000/-\n";
        }
        if(jCheckBox37.isSelected())
        {
            amount1+=850000;
            msg1+="Spinal Fusion: 850000/-\n";
        }
        String s1=jTextField1.getText();
        int a=Integer.parseInt(s1);
        if(jRadioButton1.isSelected())
        {
            amount2+=9000*a;
            msg+="Full Electric Bed room"+a+"days: "+ 9000*a+"/-\n";
        }
        if(jRadioButton2.isSelected())
        {
            amount2+=8000*a;
            msg+="Semi Electric Bed room"+a+"days: "+ 8000*a+"/-\n";
        }
        if(jRadioButton3.isSelected())
        {
            amount2+=6000*a;
            msg+="Manual Bed room "+a+" days: "+ 6000*a+"/-\n";
        }
        float totalAmount = amount+amount1+amount2;
        JOptionPane.showMessageDialog(this,"************************************************************************************\n"+"                                        Hospital Bill Charges                                   \n"+"************************************************************************************\n"+msg+msg1+msg2+"************************************************************************************\n"+"                                           Total Bill Charges                                   \n"+"************************************************************************************\n"+"\nTotal Scan/Test Bill: "+amount+ "/-"+"\nTotal Surgeries Bill: "+amount1+ "/-"+"\nTotal Room Bill: "+amount2+ "/-");
        JOptionPane.showMessageDialog(this,"\nTotal Bill: "+(totalAmount));
        String patID1 = patID.getText();
        String firstname1 = firstname.getText();
        String secondname1 = secondname.getText();
        String age1 = age.getText();
        try (Statement stmt = con.createStatement()) {
                String dbop = "INSERT INTO BILL VALUES('"+ patID1 +"','"+ firstname1 +"','"+ secondname1 +"','"+ age1 +"','"+ totalAmount +"')";
                stmt.execute(dbop);
                stmt.close();
                setVisible(false);
                new bill().setVisible(true);
            }
        catch (SQLException ex) {
            Logger.getLogger(doctorform.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //JOptionPane.showMessageDialog(this,msg1+"\n\n\nTotal Surgeries Bill: "+amount1+ "/-");
        //JOptionPane.showMessageDialog(this,msg2+"\n\n\nTotal Room Bill: "+amount2+ "/-");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox28ActionPerformed

    private void jCheckBox21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox21ActionPerformed

    private void jCheckBox27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox27ActionPerformed

    private void jCheckBox30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox30ActionPerformed

    private void jCheckBox31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox31ActionPerformed

    private void jCheckBox35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox35ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String patid = patID.getText();
        try
        {
          Statement st=con.createStatement();
          ResultSet rs=st.executeQuery("SELECT * FROM PATIENT where patientID='"+patid+"'");
          if(rs.next())
          {
              patID.setText(rs.getString(1));
              firstname.setText(rs.getString(2));
              secondname.setText(rs.getString(3));
              age.setText(rs.getString(4));
          }
          else
              JOptionPane.showMessageDialog(null,"Patient Id is not present");
        }
        catch(Exception ex)
        {
            Logger.getLogger(doctorform.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_searchActionPerformed

    private void patIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patIDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new receptionist().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    public void actionPerformed(ActionEvent e)
    {
        //String msg="";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField patID;
    private javax.swing.JButton search;
    private javax.swing.JTextField secondname;
    // End of variables declaration//GEN-END:variables
}
