/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsystem;
import java.lang.*;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Shathiya Geerthi
 */
public class editdoctor extends javax.swing.JFrame {

    /**
     * Creates new form editdoctor
     */
    Connection con;
    public editdoctor() {
        initComponents();
        createConnection();
    }
    void createConnection()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/nikildb?autoReconnect=true&useSSL=false","root","Nikil@1492");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(doctorform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex){
            Logger.getLogger(doctorform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        docID = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        secondname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        phonenumber = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        qualification = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        bloodgroup = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        department = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        shift = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        joiningdate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/back (2).png"))); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 514, 137, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter the DoctorId to edit");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 55, 247, -1));

        docID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docIDActionPerformed(evt);
            }
        });
        getContentPane().add(docID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 114, 35));

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 122, 230, 30));

        secondname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondnameActionPerformed(evt);
            }
        });
        getContentPane().add(secondname, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 122, 240, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 122, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Second Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 122, 120, 30));

        phonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumberActionPerformed(evt);
            }
        });
        getContentPane().add(phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 229, 230, 30));

        gender.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", "Others" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 229, 130, 30));

        qualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualificationActionPerformed(evt);
            }
        });
        getContentPane().add(qualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 179, 240, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 176, 40, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Qualification");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 176, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 229, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gender");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 229, 70, 30));
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 179, 230, 30));

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 280, 650, 30));

        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 340, 240, 30));

        bloodgroup.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        bloodgroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Blood Group", "AB+", "AB-", "A+", "A-", "B+", "B-", "O+", "O-" }));
        bloodgroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodgroupActionPerformed(evt);
            }
        });
        getContentPane().add(bloodgroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 338, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("City");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 337, 40, 30));

        department.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Cardiology", "Neurology", "Accident and Emergency", "General Surgery", "Dentist" }));
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });
        getContentPane().add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 389, 150, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Shift");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 388, 50, 30));

        shift.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        shift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Morning", "Evening", "Night" }));
        shift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftActionPerformed(evt);
            }
        });
        getContentPane().add(shift, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 389, 90, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Blood Group");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 337, 110, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 277, 70, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Department");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 392, 100, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Joining Date");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 445, 110, -1));

        joiningdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joiningdateActionPerformed(evt);
            }
        });
        getContentPane().add(joiningdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 443, 240, 33));

        jButton1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 513, 146, 59));

        jButton2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 515, -1, 58));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/logodoc.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, 440, 430));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/Black.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 1230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new doctor().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void secondnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondnameActionPerformed

    private void phonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumberActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        String selectedValue=gender.getSelectedItem().toString();        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void qualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qualificationActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void bloodgroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodgroupActionPerformed
        String selectedValue=bloodgroup.getSelectedItem().toString();       // TODO add your handling code here:
    }//GEN-LAST:event_bloodgroupActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        String selectedValue=department.getSelectedItem().toString();        // TODO add your handling code here:
    }//GEN-LAST:event_departmentActionPerformed

    private void shiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftActionPerformed
        String selectedValue=shift.getSelectedItem().toString();        // TODO add your handling code here:
    }//GEN-LAST:event_shiftActionPerformed

    private void joiningdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joiningdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joiningdateActionPerformed

    private void docIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /*String docid = docID.getText();
        try
        {
          Statement st=con.createStatement();
          ResultSet rs=st.executeQuery("SELECT * FROM DOCTOR where docID='"+docid+"'");
          if(rs.next())
          {
              docID.setText(rs.getString(1));
              firstname.setText(rs.getString(2));
              secondname.setText(rs.getString(3));
              age.setText(rs.getString(4));
              qualification.setText(rs.getString(5));
              phonenumber.setText(rs.getString(6));
              gender.setSelectedItem(rs.getString(7));
              address.setText(rs.getString(8));
              bloodgroup.setSelectedItem(rs.getString(9));
              city.setText(rs.getString(10));
              department.setSelectedItem(rs.getString(11));
              shift.setSelectedItem(rs.getString(12));
              joiningdate.setText(rs.getString(13));
          }
          else
              JOptionPane.showMessageDialog(null,"doctorId is not present");
        }
        catch(Exception ex)
        {
            Logger.getLogger(doctorform.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        String docID1 = docID.getText();
        String firstname1 = firstname.getText();
        String secondname1 = secondname.getText();
        String age1 = age.getText();
        String qualification1 = qualification.getText();
        String phonenumber1 = phonenumber.getText();
        String gender1 = gender.getSelectedItem().toString();
        String address1 = address.getText();
        String bloodgroup1 = bloodgroup.getSelectedItem().toString();
        String city1 = city.getText();
        String department1 = department.getSelectedItem().toString();
        String shift1 = shift.getSelectedItem().toString();
        String joiningdate1 = joiningdate.getText();
        try
        {
            Statement st=con.createStatement();
            st.executeUpdate("UPDATE DOCTOR SET FIRSTNAME='"+firstname1+"',SECONDNAME='"+secondname1+"',AGE='"+age1+"',QUALIFICATION='"+qualification1+"',PHONENUMBER='"+phonenumber1+"',GENDER='"+gender1+"',ADDRESS='"+address1+"',BLOODGROUP='"+bloodgroup1+"',CITY='"+city1+"',DEPARTMENT='"+department1+"',SHIFT='"+shift1+"',JOININGDATE='"+joiningdate1+"' where docID='"+docID1+"'");
            JOptionPane.showMessageDialog(null,"Succesfully Updated");
            setVisible(false);
            new editdoctor().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String docid = docID.getText();
        try
        {
          Statement st=con.createStatement();
          ResultSet rs=st.executeQuery("SELECT * FROM DOCTOR where docID='"+docid+"'");
          if(rs.next())
          {
              docID.setText(rs.getString(1));
              firstname.setText(rs.getString(2));
              secondname.setText(rs.getString(3));
              age.setText(rs.getString(4));
              qualification.setText(rs.getString(5));
              phonenumber.setText(rs.getString(6));
              gender.setSelectedItem(rs.getString(7));
              address.setText(rs.getString(8));
              bloodgroup.setSelectedItem(rs.getString(9));
              city.setText(rs.getString(10));
              department.setSelectedItem(rs.getString(11));
              shift.setSelectedItem(rs.getString(12));
              joiningdate.setText(rs.getString(13));
          }
          else
              JOptionPane.showMessageDialog(null,"doctorId is not present");
        }
        catch(Exception ex)
        {
            Logger.getLogger(doctorform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editdoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editdoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editdoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editdoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editdoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> bloodgroup;
    private javax.swing.JTextField city;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JTextField docID;
    private javax.swing.JTextField firstname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField joiningdate;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JTextField qualification;
    private javax.swing.JTextField secondname;
    private javax.swing.JComboBox<String> shift;
    // End of variables declaration//GEN-END:variables
}
